### ISSUE TITLE
Edit Launcher?

### ISSUE THREAD

**Issue by superpt** [PrinceFroggy/GoKart#3]
A lit bit more info? What addresses should be edited??

Thanks excelent work here!

**Comment by gentle-shao** [comment]
There's no IP address in "Launcher",you need to edit Kartrider.exe.
But the server program is incomplete,so it won't work.

**Comment by superpt** [comment]
Well I am a C# developer, and I loved the game, I might try and give it a go...

**Comment by RayKoopa** [comment]
This repository is just a crappy rip from another project taken offline a while ago due to DMCA issues with Nexon, it won't help you much with anything. And just in case you want to direct KartRider to another game server, simply add a `<server addr='127.0.0.1:39311'/>` element to a `KartRider.xml` in the game's directory.

**Comment by PrinceFroggy** [comment]
It was not a rip. I downloaded it when it got public since the dev's were dumb af.

**Comment by RayKoopa** [comment]
Yeah, because you added nothing valuable after you _ripped_ the repository before it went private.

**Comment by PrinceFroggy** [comment]
Thanks captain obvious. This src works just fine though :)
